# Generated by Django 4.1.3 on 2022-12-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_det',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='user_det',
            name='fullname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='user_det',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='user_det',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
