# Generated by Django 4.1.3 on 2022-12-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_user_det_email_user_det_fullname_user_det_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_det',
            name='address',
            field=models.CharField(default='36 apn', max_length=200),
        ),
        migrations.AlterField(
            model_name='user_det',
            name='email',
            field=models.EmailField(default='kc@', max_length=254),
        ),
        migrations.AlterField(
            model_name='user_det',
            name='fullname',
            field=models.CharField(default='kc', max_length=200),
        ),
        migrations.AlterField(
            model_name='user_det',
            name='phone',
            field=models.CharField(default='123', max_length=10),
        ),
    ]
