# Generated by Django 4.1.3 on 2022-12-08 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_user_det_address_alter_user_det_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_det',
            new_name='User_details',
        ),
    ]
